version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_DB: transportation-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transportation-db
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  pgdata: